"""
agents/hitl_and_assembler.py — Human-in-the-loop + Final Assembler nodes.

HITL node: Sets awaiting_human=True and returns. The graph interrupts here.
The UI reads the draft outputs, collects human feedback, then resumes.
Human can: approve / edit / reject.

Low fit warning node: Fires when fit score < 40. Asks human whether to proceed.

Assembler node: Combines everything into the final markdown package.
"""

from state import GraphState, HumanFeedback


# ── Low fit warning ───────────────────────────────────────────────────────────

def low_fit_warning_node(state: GraphState) -> dict:
    """
    Triggered when fit score < 40.
    Sets awaiting_human=True so the UI can ask the user whether to proceed anyway.
    The UI should present the score and gaps, then let the user decide.
    """
    log = list(state.get("agent_log", []))
    fit_data = state.get("fit_score", {})
    score = fit_data.get("score", 0)
    gaps = fit_data.get("gaps", [])

    log.append(f"LOW_FIT_WARNING: Score {score} is below 40. Pausing for human decision.")

    warning_msg = (
        f"⚠️  Low fit detected (score: {score}/100).\n\n"
        f"Main gaps:\n" + "\n".join(f"  • {g}" for g in gaps) +
        "\n\nDo you want to proceed with tailoring anyway? "
        "The application may be a long shot, but the assistant can still help."
    )

    return {
        "awaiting_human": True,
        "agent_log": log,
        "guardrail_message": warning_msg,  # reuse field to surface message to UI
    }


# ── HITL review node ──────────────────────────────────────────────────────────

def hitl_review_node(state: GraphState) -> dict:
    """
    Presents the draft CV + cover letter to the human for review.
    Sets awaiting_human=True — the graph.interrupt() call in graph.py
    will pause execution here until the UI resumes with feedback.
    """
    log = list(state.get("agent_log", []))
    log.append("HITL: Pausing for human review. Awaiting approve/edit/reject.")

    return {
        "awaiting_human": True,
        "agent_log": log,
    }


# ── Final assembler ───────────────────────────────────────────────────────────

def assembler_node(state: GraphState) -> dict:
    """
    Assembles the final markdown package from all agent outputs.
    Incorporates any human edits if provided.
    """
    log = list(state.get("agent_log", []))
    log.append("ASSEMBLER: Building final output package.")

    fit_data = state.get("fit_score", {})
    cv_data = state.get("tailored_cv", {})
    cl_data = state.get("cover_letter", {})
    feedback = state.get("human_feedback", {})

    role_title = state.get("role_title", "the role")
    company_name = state.get("company_name", "the company")

    score = fit_data.get("score", "N/A")
    recommendation = fit_data.get("recommendation", "N/A")
    strengths = fit_data.get("strengths", [])
    gaps = fit_data.get("gaps", [])
    kw = fit_data.get("keyword_analysis", {})

    # Use human-edited versions if provided
    final_cv_text = (
        feedback.get("edited_cv")
        if feedback and feedback.get("edited_cv")
        else _format_cv(cv_data, role_title, company_name)
    )

    final_cl_text = (
        feedback.get("edited_cover_letter")
        if feedback and feedback.get("edited_cover_letter")
        else cl_data.get("full_text", "")
    )

    package = f"""# Job Application Package
## {role_title} at {company_name}

---

## Fit Analysis

**Score:** {score}/100 — {recommendation.replace("_", " ").title()}

**Strengths:**
{chr(10).join(f"- {s}" for s in strengths)}

**Gaps to address:**
{chr(10).join(f"- {g}" for g in gaps)}

**Keywords matched:** {", ".join(kw.get("matched_keywords", [])) or "None identified"}
**Keywords added:** {", ".join(kw.get("missing_keywords", [])[:5]) or "None"}

---

## Tailored CV

{final_cv_text}

---

## Cover Letter

**Subject:** {cl_data.get("subject_line", "")}

{final_cl_text}

---

*Generated by Job Application Assistant · Review all content before submitting.*
"""

    if feedback and feedback.get("feedback_notes"):
        package += f"\n**Your notes:** {feedback['feedback_notes']}\n"

    log.append("ASSEMBLER: Final package assembled successfully.")

    return {
        "final_package": package,
        "awaiting_human": False,
        "agent_log": log,
    }


def _format_cv(cv_data: dict, role_title: str, company_name: str) -> str:
    """Format the TailoredCVOutput dict as readable markdown."""
    if not cv_data:
        return "_CV data not available._"

    summary = cv_data.get("summary", "")
    bullets = cv_data.get("tailored_bullets", [])
    skills = cv_data.get("skills_section", [])
    changes = cv_data.get("changes_made", [])

    lines = []
    if summary:
        lines.append(f"**Professional Summary**\n{summary}\n")
    if bullets:
        lines.append("**Key Experience**")
        lines.extend(f"- {b}" for b in bullets)
        lines.append("")
    if skills:
        lines.append(f"**Skills:** {', '.join(skills)}\n")
    if changes:
        lines.append("**Changes made by AI:**")
        lines.extend(f"- _{c}_" for c in changes)

    return "\n".join(lines)
